# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)t

dog1 = Dog.create(name: "Callcipher", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog2 = Dog.create(name: "Cappuccino", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog3 = Dog.create(name: "Caster", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")


dog3 = Dog.create(name: "Mechitas", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog4 = Dog.create(name: "Dante", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog5 = Dog.create(name: "Puppy", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")


dog6 = Dog.create(name: "El negro", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog7 = Dog.create(name: "Mitzi", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog8 = Dog.create(name: "Dalia", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")


dog9 = Dog.create(name: "Zeus", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog10 = Dog.create(name: "Thor", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog11 = Dog.create(name: "Poseidon", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")


dog12 = Dog.create(name: "Pikachu", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog13 = Dog.create(name: "Evee", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog14 = Dog.create(name: "Vaporeon", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")


dog15 = Dog.create(name: "Charizad", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog16 = Dog.create(name: "Flaeron", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog17 = Dog.create(name: "Sylveon", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")


dog18 = Dog.create(name: "Vulpix", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog19 = Dog.create(name: "Ninetales", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog20 = Dog.create(name: "Stella", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")

dog21 = Dog.create(name: "Canello", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México")
dog22 = Dog.create(name: "Crazy", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused")
dog23 = Dog.create(name: "Silver", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México")




dog24 = Dog.create(name: "Jordi", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog25 = Dog.create(name: "Bones", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog26 = Dog.create(name: "Mini", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog27 = Dog.create(name: "Butcher", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog28 = Dog.create(name: "Hunter", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog29 = Dog.create(name: "Squirtle", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog30 = Dog.create(name: "Bulbaseur", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog31 = Dog.create(name: "Onix", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog32 = Dog.create(name: "Perla", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog33 = Dog.create(name: "Bombón", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog34 = Dog.create(name: "Pinto", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog35 = Dog.create(name: "Dámata", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog36 = Dog.create(name: "Mister", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog37 = Dog.create(name: "Barbara", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog38 = Dog.create(name: "Salamandra", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog39 = Dog.create(name: "Abi", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog40 = Dog.create(name: "Abichuela", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog41 = Dog.create(name: "Tutti", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog42 = Dog.create(name: "Tuttifruti", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog43 = Dog.create(name: "Beauty", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog44 = Dog.create(name: "Wey", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog45 = Dog.create(name: "Oye tu", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog46 = Dog.create(name: "Solovino", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 1)
dog47 = Dog.create(name: "El Don", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)

dog48 = Dog.create(name: "Zully", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog49 = Dog.create(name: "Bu", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 0)
dog50 = Dog.create(name: "Kira", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 0)

dog51 = Dog.create(name: "Simba", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay", color: "I'm black with white, my hair is large and my eyes are blue", gender: "Male", age: 5, size: "Large", sterilized: false, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 1)
dog52 = Dog.create(name: "Nala", breed: "Siberian Husky", description: "I am a beatiful not so well behaved dog that needs a place with a warm family to stay, I bark a lot but it is becaused Im stressed", color: "I'm brown with white, my hair is large and my eyes are green", gender: "Female", age: 2, size: "Medium", sterilized: true, vaccined: true, urgent: false, city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopter_requirements: "A lot of patience because this dog was abused", adopted: 0)
dog53 = Dog.create(name: "Scar", breed: "Siberian Husky", description: "I am a beatiful well behaved dog that needs a place with a warm family to stay, I don't bark a lot and I know several tricks, like to sit and give the paw", color: "I'm dark gray with white, my hair is large and my eyes are yellowish", gender: "Male", age: 1, size: "Medium", sterilized: false, vaccined: true, urgent: true, adopt_before: "2016-02-01", city: "San Luis Potosí", state: "San Luis Potosí", country: "México", adopted: 0)
